### ISSUE TITLE
分派物資 新增頁 兩個dropdown list黏在一起

### ISSUE THREAD

**Issue by aiueoH** [aiueoH/dmm#11]
![image](https://cloud.githubusercontent.com/assets/5312035/13069655/4f4fec92-d4c1-11e5-98d0-a5864a89a759.png)

**Comment by aiueoH** [comment]
改一下 size 就好了

![image](https://cloud.githubusercontent.com/assets/5312035/13069696/9a3d632e-d4c1-11e5-99c1-4e7dd8e4238a.png)

**Comment by GeorgioWan** [comment]
忽略你
